// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/easy-health/pkg/api"
	"github.com/easy-health/pkg/api/handler"
	"github.com/easy-health/pkg/config"
	"github.com/easy-health/pkg/db"
	"github.com/easy-health/pkg/repository"
	"github.com/easy-health/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	doctorRepository := repository.NewDoctorRepository(gormDB)
	doctorUseCase := usecase.NewDoctorUseCase(doctorRepository)
	doctorHandler := handler.NewDoctorHandler(doctorUseCase)
	serverHTTP := http.NewServerHTTP(userHandler, doctorHandler)
	return serverHTTP, nil
}
